CLEARSCREEN.

SET SPOT0 TO SHIP:GEOPOSITION.

UNTIL SHIP:APOAPSIS > 80000 {

	SET SPOT1 TO SHIP:GEOPOSITION.
	SET SURFACE_DISTANCE TO BODY:RADIUS * ARCCOS(SIN(SPOT0:LAT*CONSTANT:DEGTORAD)*SIN(SPOT1:LAT*CONSTANT:DEGTORAD) + COS(SPOT0:LAT*CONSTANT:DEGTORAD)*COS(SPOT1:LAT*CONSTANT:DEGTORAD)*COS(ABS(SPOT1:LNG*CONSTANT:DEGTORAD-SPOT0:LNG*CONSTANT:DEGTORAD))).
	PRINT "Spot0: "+SPOT0 AT(0,5).
	PRINT "Spot1: "+SPOT1 AT(0,6).
	PRINT "Distance: "+ROUND(SURFACE_DISTANCE,0) AT (0,8).
}

